### ISSUE TITLE
Formatting for The Line Between Data-Vis and Data-Art.

### ISSUE THREAD

**Issue by knowuh** [lisacharlotterost/lisacharlotterost.github.io#4]
I want to assign your post ["Meaning and beauty …"](http://lisacharlotterost.github.io/2015/12/19/Meaning-and-Beauty-in-Data-Vis/) for some reading to a spring class, because I think it asks great questions. 

As part of that, I also wanted them to read ["The line between..."](http://lisacharlotterost.github.io/2015/12/14/The-Line-between-Data-Vis-And-Data-Art/) . But the layout wen't wonky. I am just guessing, but possibly its just be an extra blank line at the start of the file before the YML junk?

**Comment by lisacharlotterost** [comment]
Thank you! I feel honoured that my posts are a reading assignment and hope they help. 
Sorry for the delay; it's fixed now: http://lisacharlotterost.github.io/2015/12/14/The-Line-between-Data-Vis-And-Data-Art/
